apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nnd2kxkle-nodejs 
  janus-idp.io/tekton: nnd2kxkle-nodejs
  backstage.io/kubernetes-id: nnd2kxkle-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nnd2kxkle-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml