apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nnd2kxkle-nodejs
  janus-idp.io/tekton: nnd2kxkle-nodejs
  backstage.io/kubernetes-id: nnd2kxkle-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nnd2kxkle-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
