apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nnd2kxkle-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nnd2kxkle-nodejs 
  name: nnd2kxkle-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nnd2kxkle-nodejs 
